### PR TITLE
Using (real) keyboard in demo, Build improvements (as per email discussion)

### PR DESCRIPTION
**Pull request by aenchevich**
This patch contains:
 - Build improvements as per our email discussion: DEBUG, no parallel build race condition, allow cross-compilation of demo.
 - Using (real) keyboard in demo.
 - Illustrating proper usage of hal_deinit in main.c.

### CODE REVIEW

**Comment by kisvegabor** [comment]
Hi,

Is is possible to add SDL_deinit to monitor.c directly?

**Comment by kisvegabor** [comment]
I just saw the related Pull request in lv_drivers and I see the full picture now.

So my question is: what is the advantage of the proposed solution to the current one? For me it seems more complicated because the user need to deal with driver related things and need to know SDL too. Currently it is hidden in monitor.c.

**Comment by aenchevich** [comment]
1. You are right, the solution is not perfect, and yes, I agree that it would be best if HAL initialization specifics (in this case SDL calls) were not in main.

2. However ... At present the user already has to "know SDL" because main.c includes SDL2.h and calls SDL functions such as SDL_CreateThread and SDL_Delay.

3. In this context, the proposed merge does not make the situation worse, and even slightly improves it, because:
	- it shows that board-level 'hardware' init calls (SDL_Init in this case) belong in hal_init;
	- it improves the code logic, because it moves the SDL initialization from monitor.c where it did not belong (because it is related to the entire SDL usage, not just the monitor);
	- it improves the code functionally because, now, if the user decided, inside hal_init to swap the order of calls, and initialize the mouse or the keyboard first, and then the monitor - we would end up using a non-initialized SDL :) 

4. Seeing how we both agree that HAL initialization should not be in main I would like to propose the following (which would have been my next pull request :)  I just did not want to throw at you everything at once! )

Based on knowledge about the system and the build options that the user chooses, we will use a specific hal_init implementation. I think that an SDL2-based impl and a fbdev impl can be added by default. 

Then, in main.c, where we currently have this:
```
	void hal_init(void)
	{
		<some HAL specific code, curently SDL2-based>
	}
	
	int main(void)
	{
		hal_init();
		...
	}
```
, we would have this:
```
	void hal_init(void);

	#if USE_FBDEV
	#include hal_init_fbdev.cc
	#else
	#include hal_init_SDL2.cc
	#endif

	int main(void)
	{
		hal_init();
		...
	}
```
This way main will be clean and equally structured for all implementations, and particular HAL init code will be kept in it's own place where users can examine it and use as example of their own implementation.

The above assumes SDL2 is the default and does not require the user to select it explicitly. If you want we can be strict and do this:
```
	#if USE_FBDEV
	#include hal_init_fbdev.cc
	#elif USE_SDL2
	#include hal_init_SDL2.cc
	#else
	#error "You need to specify your system HAL layer."
	#endif
```

**Comment by aenchevich** [comment]
I wanted to update this pull request but it seems I have created a new one which has all of the changes in this one + what I proposed in my previous comment...I am not sure how to correct this, hope it's not a huge problem, because the new pull request has all the code?  It's  just missing the comments/discussion above

**Comment by aenchevich** [comment]
Everything that's here is already in pull request 18. Closing.

**Pull request closed without merging**
